spring:
  application:
    name: member

  # Member 模块数据库连接配置
  datasource:
    url: 'jdbc:mysql://124.223.55.166:3306/railway-ticketing-system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8'
    username: oceana_dev
    password: '${DB_PASSWORD}'
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001
  servlet:
    context-path: /member

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{LOG_ID}] %-5level %logger{36} - %msg%n'
