spring:
  application:
    name: batch

  main:
    banner-mode: off

  # Batch模块数据库连接配置
  datasource:
    url: 'jdbc:mysql://124.223.55.166:3306/railway_ticketing_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8'
    username: oceana_dev
    password: '${DB_PASSWORD}'
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8003
  servlet:
    context-path: /batch

mybatis-plus:
  global-config:
    banner: false

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{LOG_ID}] %-5level %logger{36} - %msg%n'
  level:
    root: WARN
    com.gjq.train.batch: INFO
